### ISSUE TITLE
pricefeedの書き込み先ブロックチェーンがテストネットの現バージョンと一致していないためcdpのcreateで価格情報が参照できずに失敗する

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/botany#109]
@KimuraYu45z cc: @Senna46 @taro04 

おそらく、`.env`ファイルの中のchain-idの指定が、古いテストネットを指していて、それを現バージョンのテストネットの`jpyx-3-test`に書き換える必要があるのかな？と思っているのですが、他に何か注意すべき点があれば、ご指摘頂けると助かります。

ノードの動作がhost直結に変わったと思うので、RestURLの指定を`.env`ファイルの中で変更したり、docker-compose.ymlの記述等見直す必要もある？

```
root@jpyx-test-a:~/jpyx# jpyxd tx cdp create-cdp 10ubtc 10jpyx ubtc-a --from main --chain-id jpyx-3-test
{"body":{"messages":[{"@type":"/botany.cdp.MsgCreateCdp","sender":"jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt","collateral":{"denom":"ubtc","amount":"10"},"principal":{"denom":"jpyx","amount":"10"},"collateral_type":"ubtc-a"}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
{"height":"225727","txhash":"A19DA88A04CE343A22EA638C1E3AE6A32E99BEAFF44E6761081393FE0F483EFB","codespace":"cdp","code":19,"data":"","raw_log":"failed to execute message; message index: 0: ubtc: no price found for collateral","logs":[],"info":"","gas_wanted":"200000","gas_used":"48809","tx":null,"timestamp":""}
```

**Comment by YasunoriMATSUOKA** [comment]
@KimuraYu45z cc: @Senna46 @taro04 
`docker-compose.yml`, `.env`ファイルの修正を、aのノード上で試して、再度pricefeedの起動を試みたのですが、docker-compose psの結果はUpになるものの、コンテナの中でNode.jsのプログラムがエラーで死んでいるようです。

cosmos-client-tsやbotany-clientのバージョンがマッチしていない？＆記述が古い？あたりが原因としてありそうで、telescopeやtelescope-extensionの記述を参考に同様に修正を試みようと思います。

```
root@jpyx-test-a:~/pricefeed# docker logs pricefeed_pricefeed_1
[2021-09-30T05:42:00.081Z] (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'v1beta1' of undefined
    at Object.fromObject [as /cosmos.auth.v1beta1.BaseAccount] (/node_modules/cosmos-client/cjs/proto.js:1002:65)
    at Object.unpackAny (/node_modules/cosmos-client/cjs/types/codec/module.js:16:57)
    at /price-oracle.js:89:87
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
[2021-09-30T05:42:00.083Z] (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[2021-09-30T05:42:00.083Z] (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2021-09-30T05:43:00.017Z] (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'v1beta1' of undefined
    at Object.fromObject [as /cosmos.auth.v1beta1.BaseAccount] (/node_modules/cosmos-client/cjs/proto.js:1002:65)
    at Object.unpackAny (/node_modules/cosmos-client/cjs/types/codec/module.js:16:57)
    at /price-oracle.js:89:87
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2021-09-30T05:43:00.017Z] (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
